export const TEST = 'TEST';
export const TOGGLE_ERROR_MODAL = 'TOGGLE_ERROR_MODAL';
export const GET_DATA_FROM_DB = 'GET_DATA_FROM_DB';
export const SET_CURRENT_GALLERY_INDEX = 'SET_CURRENT_GALLERY_INDEX';
export const TOGGLE_GALLERY_MODAL = 'TOGGLE_GALLERY_MODAL';
export const GET_DRAWINGS_FROM_DB = 'GET_DRAWINGS_FROM_DB';